### ISSUE TITLE
CI/CD Flow 구성

### ISSUE THREAD

**Issue by SAgiKPJH** [SagiK-Repository/Learn-Git-Lab-CICD#11]
- 다음 중 사전 작업 
  - https://github.com/SagiK-Repository/Learn-Git-Lab-CICD/issues/4
  - https://github.com/SagiK-Repository/Learn-Git-Lab-CICD/issues/8

**Comment by SAgiKPJH** [comment]
# ⏭️1차 CI/CD 동작
### 목표
- Build : Project Build Check
- Test : Project Test Check
- CI/CD Brantch : adc60-master
- 파이프 라인 결과 Slack에 알람 오도록 구현



## ⏺️.gitlab-ci.yml

```yml
before_script:
  - git config --global core.longpaths true


stages:
  - build
  - test
  - end


build:
  stage: build
  tags:
    - adc60
  variables:
    DAQ_SOLUTION_PATH: ./Src/Mirero.RecipeCreator.sln
    ADC_SOLUTION_PATH: ./Src/ADC/Mirero.ADC.App.sln
  script:
    - dotnet build $DAQ_SOLUTION_PATH --configuration Release
    - dotnet build $ADC_SOLUTION_PATH --configuration Release
  only:
    - adc-master

test:
  stage: test
  tags:
    - adc60
  variables:
    TEST_PROJECT_PATH: ./Src/ADC/Tests/Client.Business.UnitTest/Client.Business.UnitTest.csproj
  script:
    - dotnet test $TEST_PROJECT_PATH --configuration Release
  only:
    - adc-master


slack_notification:
  stage: end
  script:
    - echo 'slack_notification'
  only:
    - adc-master
```
![image](https://github.com/SagiK-Repository/Learn-Git-Lab-CICD/assets/66783849/299f40f2-0626-4618-8809-ed7e07ec62b4)


<br><Br>

## ⏹️Slack 알람 연동 방법

- Slack 알람연동 방법 [참조 링크](https://medium.com/@Rando209/how-to-integrate-gitlab-with-slack-slack%EA%B3%BC-gitlab-%EC%97%B0%EB%8F%99%ED%95%98%EA%B8%B0-8d4958d7e57f)

### Slack 설정

- https://slack.com/apps 접속
- WebHook 검색하여 수신 웹후크 추가 (또는 Slack 앱에서 WebHook 검색하여 추가)  
![image](https://github.com/SagiK-Repository/Learn-Git-Lab-CICD/assets/66783849/0f309f89-e9bd-48e4-88bd-e7cc7f838632)  
- 수신 웹후크 추가 후  
![image](https://github.com/SagiK-Repository/Learn-Git-Lab-CICD/assets/66783849/b7cbb91c-965e-444f-9d35-193d88c67f03)  
- 채널, 이미지, 이름 설정  
![image](https://github.com/SagiK-Repository/Learn-Git-Lab-CICD/assets/66783849/909ece40-e24a-41db-a669-283d4cc2198d)  
- Slack 웹 후크 URL 기억할 것.

<br><Br>

### GitLab 설정

- GitLab -> 프로젝트 저장소 -> 설정 -> 연동
![image](https://github.com/SagiK-Repository/Learn-Git-Lab-CICD/assets/66783849/542639cd-5b3a-4675-8258-b2325e9a9c1a)  
- Slack notifications 선택  
![image](https://github.com/SagiK-Repository/Learn-Git-Lab-CICD/assets/66783849/849219f5-63bd-427e-bb27-5c8b6a9e666e)  
- Enable Check., PipeLine Check, WeebHook 기입, Brantch 선택  
![image](https://github.com/SagiK-Repository/Learn-Git-Lab-CICD/assets/66783849/860cfe6b-6aa3-40e8-a67c-9e3c2a7a8e05)  
- Slack 수신 결과  
![image](https://github.com/SagiK-Repository/Learn-Git-Lab-CICD/assets/66783849/8b2fcde8-d41d-4920-8c9b-d16b43f0627a)

**Comment by SAgiKPJH** [comment]
# ⏭️2차 CI/CD 동작

## 목표

- junit 활용한 Test결과 추출
- .yml 파일 관리하기 쉽게 구성
- CI/CD Flow 구성

<br><br>

## 🔃GitLabRunner 추가 설정

- GitLabRunner 실행 권한을 사용자로 변경합니다.  
![image](https://github.com/SagiK-Repository/Learn-Git-Lab-CICD/assets/66783849/4c4abc14-60f7-492e-9d0b-1a3dd43bc029)  
- 변경은 서비스 -> 속성 -> 로그온 -> ID/PS 입력  
![image](https://github.com/SagiK-Repository/Learn-Git-Lab-CICD/assets/66783849/8456ef99-adfa-4dca-87c7-a382bb9a934f)  
- GitLabRunner를 다시 Install 반드시 Stop, Uninstall을 진행하고 Install합니다.
  ```powershell
  ./gitlab-runner.exe stop
  ./gitlab-runner.exe uninstall
  ./gitlab-runner.exe install

  # CLI로 사용자 등록 방법
  # 사용자 정의 계정 Runner 설치
  .\gitlab-runner.exe install --user ENTER-YOUR-USERNAME --password ENTER-YOUR-PASSWORD 
  ```

<Br><br>


## ⏹.yml 파일 관리하기 쉽게 구성

### 스크립트를 빼서 관리하는 이유

- Local에서 빌드시 실행, CICD에서도 실행하기에, 공통적인 부분을 Powershell 실행파일로 분리합니다.
  - .gitlab-ci.yml과 실행 스크립트 분리합니다.
- As-Is
```yml
  script:
    - dotnet test $TEST_PROJECT_PATH --configuration Release
```
- To-Be
```yml
  script:
    - powershell -File ./Build.ps1
```

<br>

### CI관련 폴더 묶어 관리
- CI에 필요한 문서를 보관하여 관리합니다.
```
{솔루션}
 └─CICD
     ├─Build.ps1
     ├─Test.ps1
     └─Build-Install.ps1    
```

<br>

### Script 단계별 분리
- CICD도중 에러 발생시 어디에서 발생한지 명확하게 하기 위해 최대한 분리해서 구성합니다.
- As-Is
```powershell
dotnet build $adc_sln_path  --configuration release
```
- To-Be
```powershell
dotnet restore $adc_sln_path
dotnet build $adc_sln_path `
    --no-restore `
    --configuration release
```

<br>

### .gitlab-ci.yml 리팩토링
- Stage 명칭 명확하게 합니다.
```yml
before_script:
  - git config --global core.longpaths true

stages:
  - build
  - notification

solution.build:
  stage: build
  tags:
    - adc60
  script:
    - powershell -File ./Build.ps1
  only:
    - adc-master

slack.notification:
  stage: notification
  tags:
    - adc60
  script:
    - echo 'slack_notification'
  only:
    - adc-master
```


<Br><br>

## ⏺️️junit 활용한 Test 결과 추출 방법
- xUnit Test 프로젝트에 NugetPackage 추가
  - JunitXml.TestLogger

![image](https://github.com/SagiK-Repository/Learn-Git-Lab-CICD/assets/66783849/0edf09de-964d-4bf2-b0be-6312e017e0b2)


### Test 방법
- 다음과 같이 Test 진행합니다.
```powershell
dotnet test $adc_sln_path `
    --configuration Release `
    --no-build `
    --collect "XPlat Code Coverage" `
    --logger "junit;LogFilePath=./TestResults/logs.junit.xml;MethodFormat=Class;FailureBodyFormat=Verbose" `
    --logger "trx;LogFileName=logs.trx"
```
- 이 경우, Test 후 다음과 같이, Test 결과 내용이 담긴 폴더 및 xml 파일들이 나타납니다.  
![image](https://github.com/SagiK-Repository/Learn-Git-Lab-CICD/assets/66783849/084a3e13-81d9-47bd-89f5-e2cab2b24bb1)

<br>

### Test 프로젝트로부터 결과 종합

- 사전에 dotnet tool을 추가해야 합니다.
```powershell
dotnet tool install --global dotnet-coverage --version 17.9.6
dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.2.0

#목록 확인 (global이 없으면 현재 디렉토리에만 적용되도독 설치됩니다.)
dotnet tool list --global
```
- 이후 결과를 종합하고 커버리지 보고서 제작합니다.
```powershell
$results_dir    = join-path $root_dir ".results"
$coverage_dir   = join-path $results_dir "coverage"
$coverage_path  = join-path $coverage_dir "coverage.cobertura.merged.xml"

# 진행할 때 마다 관련 파일 삭제
Get-ChildItem -Path $root_dir -Directory -Recurse -Filter "TestResults" `
    | ForEach-Object { Write-Output $_.FullName; Remove-Item $_.FullName -Recurse -Force }
New-Item $coverage_dir -ItemType Directory -Force | Out-Null

# 코드 결과 종합, 모든 TestResults 폴더 찾아, 내부의 "*.cobertura.xml" 종합
dotnet-coverage merge "**/TestResults/*/*.cobertura.xml" `
    -f cobertura `
    -o $coverage_path

# 솔루션 코드 커버리지 보고서 제작
# 출력 형식은 Html, Badges, MarkdownSummaryGithub 3가지 추출
reportgenerator `
	-reports:$coverage_path `
	-targetdir:(Join-Path $coverage_dir "report") `
	-reporttypes:"Html;Badges;MarkdownSummaryGithub" `
    -verbosity:Info
```
- 코드 커버리지 보고서 결과는 다음과 같이 볼 수 있습니다.
  - index.htm      
  ![image](https://github.com/SagiK-Repository/Learn-Git-Lab-CICD/assets/66783849/39892291-c464-411c-8a26-60ad9ca8d41b)  
  - SummaryGithub.md  
  ![image](https://github.com/SagiK-Repository/Learn-Git-Lab-CICD/assets/66783849/f4b62fdd-77cf-46f0-9cae-0b9e96cbd7b7)  


<br><br>

### gitlab-ci.yml 추가
- 마지막으로 junit 종합결과를 gitlab에게 전달합니다.
```yml
solution.build:
  stage: build
  tags:
    - adc60
  script:
    - powershell -File ./Build.ps1
  artifacts:
    when: always
    reports:
      junit:
       - ./**/TestResults/**/logs.junit.xml
      coverage_report:
        coverage_format: cobertura
        path: ./.results/coverage/coverage.cobertura.merged.xml
  only:
    - adc-master
```
![image](https://github.com/SagiK-Repository/Learn-Git-Lab-CICD/assets/66783849/1d83dcb2-84cd-4411-8727-77c857536afa)
