### ISSUE TITLE
CI/CD Code Coverage

### ISSUE THREAD

**Issue by SAgiKPJH** [SagiK-Repository/Learn-Git-Lab-CICD#13]
# 목표
- Code Coverage Result에 나타나게 하는 것이 목적입니다.
  - Before
    - ![image](https://github.com/user-attachments/assets/c2952300-3c3a-4b42-98f6-6f33671d4edc)
  - After
    - ![image](https://github.com/user-attachments/assets/15630dcc-ed13-4dfa-873a-bdaaa37f4521)

**Comment by SAgiKPJH** [comment]
# Git-Lab Coverage?
- Git-Lab에서 CI/CD에서는 다양한 상태를 Badge 형대로 받을 수 있습니다.
  - 프로젝트 - 설정 - CI/CD - 일반 파이프라인 - Pipeline status, Coverage Report, Latest release
  - ![image](https://github.com/user-attachments/assets/410317c7-2452-4885-9fca-93aaf07673a9)
  - ![image](https://github.com/user-attachments/assets/c54343c9-02a4-4c6c-9553-44dda38261c7)
  - ![image](https://github.com/user-attachments/assets/625af3a1-0bb1-4cb3-901d-7e92b4352a67)

**Comment by SAgiKPJH** [comment]
# Coverage 값 나타나게 하는 방법
- Git-Lab CICD의 경우에는 다음과 같이 PipeLine에서 값을 지정해주면 됩니다.
```yml
test.example:
  stage: test
  script:
    - pwsh -Command "& Write-Host 'Line-Coverage = 1.41%'"
  coverage: '/Line-Coverage = \d+(?:\.\d+)?%/'
```
- 프로젝트 - Build - 파이프라인 - 방금 실행된 파이프라인 - Jobs - Coverage 확인
  - ![image](https://github.com/user-attachments/assets/6bc63b45-e920-4eec-875a-8e531069e2b3)
  - ![image](https://github.com/user-attachments/assets/fd1cea3d-773f-43ac-a6a1-2ca9890c0ec4)

**Comment by SAgiKPJH** [comment]
# Code Coverage 계산 결과 도출 방법

## junit 통한 Coverage 종합 파일(*.xml) 추출
- dotnet test에서 coverage 계산 종합해주는 junit을 활용해 진행합니다.
```bash
dotnet test $SOLUTION_PATH --configuration Release --no-build --collect "XPlat Code Coverage;Exclude=[Exclude.Project.*]*,[Python.*]*" --logger "junit;LogFilePath=./TestResults/logs.junit.xml;MethodFormat=Class;FailureBodyFormat=Verbose" --logger "trx;LogFileName=logs.trx"
```
- `Exclude=[Exclude.Project.*]*,[Python.*]*` 구문으로 제외할 프로젝트를 설정합니다.
  - Exclude.Project.~으로 시작하는 프로젝트 및 Python.~로 시작하는 프로젝트를 제외합니다.
- 각 프로젝트의 `./TestResults/logs.junit.xml`, `coverage.cobertura.xml` 파일로 나타나게 합니다.
  - 사전에 테스트 프로젝트 nuget package에 junit 설치해놓습니다.
  - ![image](https://github.com/user-attachments/assets/3834d45e-4dfd-4a4b-82ee-88d2772ffe24)
  - `coverage.cobertura.xml` 파일의 `line-rate` 값이 Coverage 값(0.00~1.00)입니다.
  - ![image](https://github.com/user-attachments/assets/5779ba69-f287-479c-89de-ce12c33213c1)

## dotnet-coverage를 통한 여러 프로젝트의 xml 파일 종합
- dotnet-coverage를 통해 여러개 프로젝트의 xml 파일을 종합할 수 있습니다.
  - https://learn.microsoft.com/ko-kr/dotnet/core/additional-tools/dotnet-coverage
- dotnet-coverage 설치
  ```bash
  dotnet tool install --global dotnet-coverage
  ```
- dotnet-coverage 실행
  ```bash
  dotnet-coverage merge "**/TestResults/*/*.cobertura.xml" -f cobertura -o (Join-Path $COVERAGE_PATH "output.xml")
  ```
- yml 구성
  ```yml
  test.coverage:
    stage: test
    script:
      - ."C:\Users\Administrator\.dotnet\tools\dotnet-coverage.exe" merge "**/TestResults/*/*.cobertura.xml" -f cobertura -o (Join-Path $COVERAGE_PATH "output.xml")
      - $coverage = (Get-Content (Join-Path ${COVERAGE_PATH} 'output.xml') | Select-String -Pattern 'line-rate="(\d+(?:\.\d+)?)"').Matches.Groups[1].Value
      - $coveragePercent = [math]::Round([double]$coverage * 100, 2)
      - pwsh -Command "& Write-Host 'Line-Coverage = $coveragePercent%'"
    coverage: '/Line-Coverage = \d+(?:\.\d+)?%/'
  ```

**Comment by SAgiKPJH** [comment]
# Test Coverage PipeLine 예시
```yml
test.coverage:
  stage: test
  variables:
    GIT_STRATEGY: none
  needs: ["solution.test"]
  tags:
    - adc60
  script:
    - ."C:\Users\Administrator\.dotnet\tools\dotnet-coverage.exe" merge "**/TestResults/*/*.cobertura.xml" -f cobertura -o (Join-Path $COVERAGE_PATH "output.xml")
    - ."C:\Users\Administrator\.dotnet\tools\reportgenerator.exe" -reports:(Join-Path $COVERAGE_PATH "output.xml") -targetdir:$COVERAGE_PATH -reporttypes:"MarkdownSummaryGithub" -verbosity:Verbose
    - $coverage = (Get-Content (Join-Path ${COVERAGE_PATH} 'output.xml') | Select-String -Pattern 'line-rate="(\d+(?:\.\d+)?)"').Matches.Groups[1].Value
    - $coveragePercent = [math]::Round([double]$coverage * 100, 2)
    - pwsh -Command "& Write-Host 'Line-Coverage = $coveragePercent%'"
  artifacts:
    when: always
    reports:
      junit:
       - ./**/TestResults/**/logs.junit.xml
      coverage_report:
        coverage_format: cobertura
        path: ./.result/coverage/SummaryGithub.md
  coverage: '/Line-Coverage = \d+(?:\.\d+)?%/'
  only:
    - adc-master
    - ci-test
```
